import {
  detectTool,
  runTool,
  type AgentToolName,
  type AgentToolResult,
  type DetectedTool,
} from "./tools";

/**
 * =========================================================
 * AGENT REQUEST
 * =========================================================
 *
 * This is the request object passed from server.ts into
 * the Nodysom AI agent.
 *
 * The controller intentionally does not call Gemini,
 * OpenRouter, Groq, or any other AI provider directly.
 *
 * server.ts remains responsible for the actual AI provider
 * implementation.
 */

export interface AgentRequest {
  /**
   * Current user message.
   */
  message: string;

  /**
   * Previous conversation messages.
   *
   * This is kept flexible because the frontend may send
   * different history formats.
   */
  history?: unknown[];

  /**
   * Stored memories.
   */
  memories?: unknown[];

  /**
   * Optional user profile.
   */
  userProfile?: {
    name?: string;

    preferredLanguage?: string;

    goals?: string;

    country?: string;

    tier?: string;

    lowDataMode?: boolean;

    interests?: string[];
  };

  /**
   * Requested language.
   *
   * Example:
   * "English"
   * "Swahili"
   */
  language?: string;
}

/**
 * =========================================================
 * AI TOOL CALL
 * =========================================================
 *
 * The AI can request one of the deterministic local tools.
 *
 * IMPORTANT:
 *
 * The actual tool execution happens in this controller.
 *
 * The AI itself does not execute arbitrary code.
 */

export interface AgentToolCall {
  /**
   * Name of the local tool.
   */
  tool: AgentToolName;

  /**
   * Optional input supplied to the tool.
   */
  input?: string;
}

/**
 * =========================================================
 * AI ANSWER
 * =========================================================
 *
 * server.ts returns this structure after calling the
 * configured AI provider.
 */

export interface AgentAIAnswer {
  /**
   * Final natural-language response.
   */
  reply: string;

  /**
   * Optional action detected by the AI.
   *
   * Examples:
   * schedule
   * reminder
   * planning
   * task
   */
  detectedAction?: any | null;

  /**
   * Optional memory candidate generated by the AI.
   */
  newMemory?: any | null;

  /**
   * Optional deterministic tool request.
   */
  toolCall?: AgentToolCall | null;
}

/**
 * =========================================================
 * AGENT RESULT
 * =========================================================
 *
 * Final result returned by runAgent().
 */

export interface AgentResult {
  /**
   * Final response shown to the user.
   */
  reply: string;

  /**
   * Whether a local tool was used.
   */
  usedTool: boolean;

  /**
   * Last tool used.
   */
  tool?: string | null;

  /**
   * Result returned by the last tool.
   */
  toolResult?: string | null;

  /**
   * Action detected by the AI.
   */
  detectedAction?: any | null;

  /**
   * New memory suggested by the AI.
   */
  newMemory?: any | null;

  /**
   * Number of processing steps used.
   */
  steps: number;

  /**
   * All unique tools used during processing.
   */
  toolsUsed: string[];
}

/**
 * =========================================================
 * AI CALLBACK
 * =========================================================
 *
 * server.ts supplies the actual AI implementation.
 *
 * IMPORTANT:
 *
 * agentController.ts does NOT call:
 *
 * Gemini
 * OpenRouter
 * Groq
 * OpenAI
 * or any external AI provider directly.
 *
 * This keeps the agent architecture modular.
 */

export type GenerateAgentAnswer = (
  request: AgentRequest,
  toolResult?: string
) => Promise<AgentAIAnswer>;

/**
 * =========================================================
 * CONSTANTS
 * =========================================================
 *
 * Maximum number of AI/tool processing cycles.
 *
 * This prevents accidental infinite loops.
 */

const MAX_AGENT_STEPS = 3;

/**
 * =========================================================
 * ALLOWED LOCAL TOOLS
 * =========================================================
 *
 * Keep an explicit allow-list.
 *
 * Even if an AI model returns an unexpected tool name,
 * the controller will never execute an unknown tool.
 */

const ALLOWED_AGENT_TOOLS: AgentToolName[] = [
  "calculator",
  "time",
  "text_stats",
];

/**
 * =========================================================
 * HELPERS
 * =========================================================
 */

/**
 * Clean any value that is expected to be a message.
 *
 * This prevents undefined/null/non-string values from
 * entering the agent pipeline.
 */

function cleanMessage(
  value: unknown
): string {
  if (
    typeof value !== "string"
  ) {
    return "";
  }

  return value.trim();
}

/**
 * Check whether a value is a valid local tool.
 */

function isAllowedTool(
  value: unknown
): value is AgentToolName {
  return (
    typeof value === "string" &&
    ALLOWED_AGENT_TOOLS.includes(
      value as AgentToolName
    )
  );
}

/**
 * Convert any tool result into short structured text
 * that can safely be passed back to the AI.
 */

function formatToolResult(
  result: AgentToolResult
): string {
  if (result.ok) {
    return (
      `Tool: ${result.tool}\n` +
      `Status: success\n` +
      `Result:\n${result.result}`
    );
  }

  return (
    `Tool: ${result.tool}\n` +
    `Status: error\n` +
    `Error:\n${result.result}`
  );
}

/**
 * =========================================================
 * TOOL RESULT MESSAGE
 * =========================================================
 *
 * Adds a tool result to the request without destroying
 * the original user message.
 *
 * The original message remains visible to the AI.
 */

function appendToolResultToRequest(
  request: AgentRequest,
  result: AgentToolResult
): AgentRequest {
  const originalMessage =
    cleanMessage(
      request.message
    );

  const formattedResult =
    formatToolResult(
      result
    );

  return {
    ...request,

    message:
      `${originalMessage}\n\n` +
      `A local tool was executed.\n` +
      `${formattedResult}`,
  };
}

/**
 * =========================================================
 * RUN AGENT
 * =========================================================
 *
 * Main Nodysom AI agent controller.
 *
 * Flow:
 *
 * User message
 *      ↓
 * Deterministic tool detection
 *      ↓
 * Run tool if required
 *      ↓
 * Return direct result OR
 *      ↓
 * Send request to AI
 *      ↓
 * AI may request local tool
 *      ↓
 * Execute tool
 *      ↓
 * Send tool result back to AI
 *      ↓
 * Final natural-language answer
 *
 * Available local tools:
 *
 * calculator
 * time
 * text_stats
 */

export async function runAgent(
  request: AgentRequest,
  generateAnswer: GenerateAgentAnswer
): Promise<AgentResult> {
  /**
   * =======================================================
   * NORMALIZE USER MESSAGE
   * =======================================================
   */

  const message =
    cleanMessage(
      request.message
    );

  /**
   * =======================================================
   * EMPTY REQUEST
   * =======================================================
   *
   * Never send an empty message to an AI provider.
   */

  if (!message) {
    return {
      reply:
        "Please enter a message so I can help you.",

      usedTool:
        false,

      tool:
        null,

      toolResult:
        null,

      detectedAction:
        null,

      newMemory:
        null,

      steps:
        0,

      toolsUsed:
        [],
    };
  }

  /**
   * =======================================================
   * CURRENT REQUEST
   * =======================================================
   */

  let currentRequest:
    AgentRequest = {
      ...request,

      message,
    };

  /**
   * =======================================================
   * AGENT STATE
   * =======================================================
   */

  let usedTool =
    false;

  let lastTool:
    AgentToolName | null =
      null;

  let lastToolResult:
    string | null =
      null;

  let detectedAction:
    any | null =
      null;

  let newMemory:
    any | null =
      null;

  const toolsUsed:
    string[] = [];

  let steps =
    0;

  /**
   * =======================================================
   * STEP 1
   * DETERMINISTIC TOOL DETECTION
   * =======================================================
   *
   * This allows simple requests to be handled locally.
   *
   * Example:
   *
   * "25 * 4"
   *
   * "what time is it"
   *
   * "count the words in this text"
   *
   * Such requests do not need an expensive AI call.
   */

  const detection =
    detectTool(
      message
    );

  /**
   * =======================================================
   * DIRECT LOCAL TOOL
   * =======================================================
   */

  if (
    detection.intent ===
    "tool"
  ) {
    const detectedTool:
      DetectedTool =
      detection;

    /**
     * Verify that the detected tool is actually allowed.
     */

    if (
      !isAllowedTool(
        detectedTool.tool
      )
    ) {
      return {
        reply:
          "I couldn't safely execute that tool.",

        usedTool:
          false,

        tool:
          null,

        toolResult:
          null,

        detectedAction:
          null,

        newMemory:
          null,

        steps:
          1,

        toolsUsed:
          [],
      };
    }

    /**
     * Execute the deterministic tool.
     */

    const toolResult =
      runTool(
        detectedTool.tool,
        detectedTool.input
      );

    /**
     * Update state.
     */

    usedTool =
      true;

    lastTool =
      detectedTool.tool;

    lastToolResult =
      toolResult.result;

    toolsUsed.push(
      detectedTool.tool
    );

    steps +=
      1;

    /**
     * =====================================================
     * TOOL FAILURE
     * =====================================================
     *
     * If a deterministic tool fails, there is no reason
     * to make another expensive AI request.
     */

    if (
      !toolResult.ok
    ) {
      return {
        reply:
          toolResult.result,

        usedTool:
          true,

        tool:
          detectedTool.tool,

        toolResult:
          toolResult.result,

        detectedAction:
          null,

        newMemory:
          null,

        steps,

        toolsUsed,
      };
    }

    /**
     * =====================================================
     * CALCULATOR
     * =====================================================
     *
     * Calculator output is already deterministic.
     *
     * No AI request is necessary.
     */

    if (
      detectedTool.tool ===
      "calculator"
    ) {
      return {
        reply:
          toolResult.result,

        usedTool:
          true,

        tool:
          detectedTool.tool,

        toolResult:
          toolResult.result,

        detectedAction:
          null,

        newMemory:
          null,

        steps,

        toolsUsed,
      };
    }

    /**
     * =====================================================
     * TIME
     * =====================================================
     *
     * The local time tool returns UTC.
     *
     * Preserve the existing behavior so the frontend
     * remains compatible.
     */

    if (
      detectedTool.tool ===
      "time"
    ) {
      return {
        reply:
          `The current UTC time is ${toolResult.result}.`,

        usedTool:
          true,

        tool:
          detectedTool.tool,

        toolResult:
          toolResult.result,

        detectedAction:
          null,

        newMemory:
          null,

        steps,

        toolsUsed,
      };
    }

    /**
     * =====================================================
     * TEXT STATISTICS
     * =====================================================
     */

    if (
      detectedTool.tool ===
      "text_stats"
    ) {
      return {
        reply:
          toolResult.result,

        usedTool:
          true,

        tool:
          detectedTool.tool,

        toolResult:
          toolResult.result,

        detectedAction:
          null,

        newMemory:
          null,

        steps,

        toolsUsed,
      };
    }
  }

  /**
   * =======================================================
   * NORMAL AI REQUEST
   * =======================================================
   *
   * Requests that are not simple deterministic tool
   * operations are sent to the AI provider.
   *
   * server.ts decides whether the provider is:
   *
   * Gemini
   * OpenRouter
   * Groq
   *
   * or another configured provider.
   */

  for (
    let step = 0;
    step < MAX_AGENT_STEPS;
    step += 1
  ) {
    /**
     * Count this processing step.
     */

    steps +=
      1;

    /**
     * -----------------------------------------------------
     * ASK AI
     * -----------------------------------------------------
     *
     * If a previous tool was executed, the tool result is
     * supplied separately as well.
     */

    const answer =
      await generateAnswer(
        currentRequest,
        lastToolResult ||
          undefined
      );

    /**
     * =====================================================
     * NORMALIZE AI RESPONSE
     * =====================================================
     */

    const aiReply =
      cleanMessage(
        answer?.reply
      );

    /**
     * =====================================================
     * PRESERVE AI METADATA
     * =====================================================
     */

    detectedAction =
      answer?.detectedAction ??
      null;

    newMemory =
      answer?.newMemory ??
      null;

    /**
     * =====================================================
     * NO TOOL REQUEST
     * =====================================================
     *
     * This means the AI has completed the request.
     */

    if (
      !answer?.toolCall
    ) {
      return {
        reply:
          aiReply ||
          "I’m ready to help. What would you like to do?",

        usedTool,

        tool:
          lastTool,

        toolResult:
          lastToolResult,

        detectedAction,

        newMemory,

        steps,

        toolsUsed,
      };
    }

    /**
     * =====================================================
     * AI REQUESTED A TOOL
     * =====================================================
     */

    const requestedTool =
      answer.toolCall.tool;

    /**
     * Normalize the tool input.
     */

    const toolInput =
      cleanMessage(
        answer.toolCall.input
      );

    /**
     * =====================================================
     * TOOL VALIDATION
     * =====================================================
     *
     * Never trust the model's requested tool name.
     *
     * Only the explicitly allowed local tools can execute.
     */

    if (
      !isAllowedTool(
        requestedTool
      )
    ) {
      return {
        reply:
          aiReply ||
          "I couldn't execute that tool.",

        usedTool,

        tool:
          lastTool,

        toolResult:
          lastToolResult,

        detectedAction,

        newMemory,

        steps,

        toolsUsed,
      };
    }

    /**
     * =====================================================
     * EXECUTE AI-REQUESTED TOOL
     * =====================================================
     */

    const result =
      runTool(
        requestedTool,
        toolInput
      );

    /**
     * Update agent state.
     */

    usedTool =
      true;

    lastTool =
      requestedTool;

    lastToolResult =
      result.result;

    /**
     * Add tool to the list only once.
     */

    if (
      !toolsUsed.includes(
        requestedTool
      )
    ) {
      toolsUsed.push(
        requestedTool
      );
    }

    /**
     * =====================================================
     * TOOL FAILURE
     * =====================================================
     */

    if (
      !result.ok
    ) {
      return {
        reply:
          result.result,

        usedTool:
          true,

        tool:
          requestedTool,

        toolResult:
          result.result,

        detectedAction,

        newMemory,

        steps,

        toolsUsed,
      };
    }

    /**
     * =====================================================
     * TOOL SUCCESS
     * =====================================================
     *
     * Give the deterministic result back to the AI.
     *
     * This allows the model to produce a natural answer
     * instead of exposing raw internal tool data.
     */

    currentRequest =
      appendToolResultToRequest(
        currentRequest,
        result
      );
  }

  /**
   * =======================================================
   * SAFETY FALLBACK
   * =======================================================
   *
   * If the model keeps requesting tools until the maximum
   * number of steps is reached, stop the loop.
   *
   * This guarantees that the backend cannot enter an
   * infinite AI → tool → AI → tool cycle.
   */

  return {
    reply:
      "I completed the available processing, but I couldn't finish the request within the allowed steps.",

    usedTool,

    tool:
      lastTool,

    toolResult:
      lastToolResult,

    detectedAction,

    newMemory,

    steps,

    toolsUsed,
  };
}
