import {
  detectTool,
  runTool,
  type AgentToolName,
  type DetectedTool,
} from "./tools";

export interface AgentRequest {
  message: string;
  history?: unknown[];
  memories?: string[];
}

export interface AgentToolCall {
  tool: AgentToolName;
  input: string;
}

export interface AgentAIContext {
  toolCallId?: string;
  toolName?: AgentToolName;
  modelContent?: unknown;
}

export interface AgentAIAnswer {
  reply: string;
  detectedAction?: AgentAction | null;
  newMemory?: string | null;
  toolCall?: AgentToolCall | null;

  /**
   * Native Gemini function-calling state.
   * This is preserved between agent steps so the
   * function result can be returned to the same
   * model turn correctly.
   */
  toolCallId?: string | null;
  modelContent?: unknown;
}

export interface AgentAction {
  type: string;
  payload?: Record<string, unknown>;
}

export interface AgentResponse {
  reply: string;
  detectedAction?: AgentAction | null;
  newMemory?: string | null;

  usedTool: boolean;
  tool?: AgentToolName | null;
  toolResult?: string | null;

  steps: number;
  toolsUsed: AgentToolName[];
}

const MAX_AGENT_STEPS = 6;
const MAX_MESSAGE_LENGTH = 4000;
const MAX_TOOL_RESULT_LENGTH = 2000;

const ALLOWED_TOOLS = new Set<AgentToolName>([
  "calculator",
  "time",
  "text_stats",
]);

function cleanText(value: unknown, maxLength: number): string {
  if (typeof value !== "string") return "";

  return value
    .replace(/\u0000/g, "")
    .trim()
    .slice(0, maxLength);
}

function sanitizeToolResult(value: unknown): string {
  if (typeof value === "string") {
    return cleanText(value, MAX_TOOL_RESULT_LENGTH);
  }

  try {
    return cleanText(
      JSON.stringify(value),
      MAX_TOOL_RESULT_LENGTH
    );
  } catch {
    return "Tool returned an unreadable result.";
  }
}

function sanitizeToolInput(value: unknown): string {
  return cleanText(value, MAX_MESSAGE_LENGTH);
}

function isAllowedTool(
  tool: unknown
): tool is AgentToolName {
  return (
    typeof tool === "string" &&
    ALLOWED_TOOLS.has(tool as AgentToolName)
  );
}

function normalizeToolCall(
  toolCall: AgentToolCall | null | undefined
): AgentToolCall | null {
  if (!toolCall) return null;

  if (!isAllowedTool(toolCall.tool)) {
    return null;
  }

  return {
    tool: toolCall.tool,
    input: sanitizeToolInput(toolCall.input),
  };
}

function normalizeDetectedTool(
  detected: DetectedTool | null
): AgentToolCall | null {
  if (!detected) return null;

  if (!isAllowedTool(detected.tool)) {
    return null;
  }

  return {
    tool: detected.tool,
    input: sanitizeToolInput(detected.input),
  };
}

export async function runAgent(
  request: AgentRequest,
  aiAnswer: (
    request: AgentRequest,
    toolResult?: string,
    context?: AgentAIContext
  ) => Promise<AgentAIAnswer>
): Promise<AgentResponse> {
  const message = cleanText(request.message, MAX_MESSAGE_LENGTH);

  if (!message) {
    return {
      reply: "Please provide a message.",
      detectedAction: null,
      newMemory: null,
      usedTool: false,
      tool: null,
      toolResult: null,
      steps: 0,
      toolsUsed: [],
    };
  }

  const safeRequest: AgentRequest = {
    ...request,
    message,
  };

  let steps = 0;

  let latestToolResult: string | undefined;

  let lastTool: AgentToolName | null = null;

  let detectedAction: AgentAction | null = null;

  let newMemory: string | null = null;

  let usedTool = false;

  const toolsUsed: AgentToolName[] = [];

  /**
   * Native Gemini state.
   *
   * These values come from the previous Gemini
   * function-call response and are passed back
   * together with the function result.
   */
  let geminiModelContent: unknown = null;
  let geminiToolCallId: string | undefined;
  let geminiToolName: AgentToolName | undefined;

  /**
   * ------------------------------------------------
   * STEP 1
   * ------------------------------------------------
   *
   * First check whether one of our deterministic
   * local tools can answer the request directly.
   *
   * Example:
   *   "calculate 25 * 4"
   *   "what time is it?"
   *   "count the words in..."
   */
  const detected = normalizeDetectedTool(
    detectTool(message)
  );

  if (detected) {
    steps++;

    usedTool = true;
    lastTool = detected.tool;

    if (!toolsUsed.includes(detected.tool)) {
      toolsUsed.push(detected.tool);
    }

    try {
      const rawResult = await runTool(
        detected.tool,
        detected.input
      );

      latestToolResult = sanitizeToolResult(rawResult);
    } catch (error) {
      latestToolResult =
        error instanceof Error
          ? cleanText(error.message, MAX_TOOL_RESULT_LENGTH)
          : "The tool failed to execute.";
    }

    /**
     * Ask Gemini to turn the tool result into a
     * natural user-facing answer.
     *
     * This is intentionally not treated as a native
     * Gemini function-response because the tool was
     * detected locally rather than generated by Gemini.
     */
    try {
      const finalResult = await aiAnswer(
        safeRequest,
        latestToolResult
      );

      if (finalResult.detectedAction) {
        detectedAction = finalResult.detectedAction;
      }

      if (finalResult.newMemory) {
        newMemory = cleanText(
          finalResult.newMemory,
          1000
        );
      }

      return {
        reply:
          cleanText(finalResult.reply, 4000) ||
          latestToolResult ||
          "Done.",
        detectedAction,
        newMemory,
        usedTool,
        tool: lastTool,
        toolResult: latestToolResult,
        steps,
        toolsUsed,
      };
    } catch {
      /**
       * If Gemini is unavailable after a successful
       * deterministic tool execution, return the
       * tool result instead of losing the result.
       */
      return {
        reply: latestToolResult || "The tool completed successfully.",
        detectedAction,
        newMemory,
        usedTool,
        tool: lastTool,
        toolResult: latestToolResult,
        steps,
        toolsUsed,
      };
    }
  }

  /**
   * ------------------------------------------------
   * STEP 2+
   * ------------------------------------------------
   *
   * No deterministic tool was detected.
   * Let Gemini decide whether a tool is necessary.
   */
  for (
    let currentStep = 0;
    currentStep < MAX_AGENT_STEPS;
    currentStep++
  ) {
    steps++;

    let modelResult: AgentAIAnswer;

    try {
      /**
       * If Gemini previously requested a tool,
       * provide the native model content + matching
       * function result context.
       */
      const context: AgentAIContext | undefined =
        geminiModelContent &&
        geminiToolCallId &&
        geminiToolName
          ? {
              modelContent: geminiModelContent,
              toolCallId: geminiToolCallId,
              toolName: geminiToolName,
            }
          : undefined;

      modelResult = await aiAnswer(
        safeRequest,
        latestToolResult,
        context
      );
    } catch (error) {
      return {
        reply:
          error instanceof Error
            ? "I couldn't complete that request right now."
            : "I couldn't complete that request right now.",
        detectedAction,
        newMemory,
        usedTool,
        tool: lastTool,
        toolResult: latestToolResult ?? null,
        steps,
        toolsUsed,
      };
    }

    /**
     * Preserve structured response information.
     */
    if (modelResult.detectedAction) {
      detectedAction = modelResult.detectedAction;
    }

    if (modelResult.newMemory) {
      newMemory = cleanText(
        modelResult.newMemory,
        1000
      );
    }

    /**
     * ------------------------------------------------
     * NO TOOL CALL
     * ------------------------------------------------
     *
     * Gemini has produced the final answer.
     */
    const normalizedToolCall = normalizeToolCall(
      modelResult.toolCall
    );

    if (!normalizedToolCall) {
      return {
        reply:
          cleanText(modelResult.reply, 4000) ||
          latestToolResult ||
          "Done.",
        detectedAction,
        newMemory,
        usedTool,
        tool: lastTool,
        toolResult: latestToolResult ?? null,
        steps,
        toolsUsed,
      };
    }

    /**
     * ------------------------------------------------
     * TOOL CALL
     * ------------------------------------------------
     */
    usedTool = true;
    lastTool = normalizedToolCall.tool;

    if (!toolsUsed.includes(normalizedToolCall.tool)) {
      toolsUsed.push(normalizedToolCall.tool);
    }

    /**
     * Save the Gemini model response and call ID.
     *
     * On the next iteration server.ts will construct
     * the corresponding functionResponse and send it
     * back to Gemini.
     */
    geminiModelContent =
      modelResult.modelContent ?? null;

    geminiToolCallId =
      cleanText(modelResult.toolCallId, 200) ||
      undefined;

    geminiToolName =
      normalizedToolCall.tool;

    /**
     * A function call without an ID cannot safely
     * participate in the native function-response
     * protocol.
     *
     * We still execute the local tool, but don't
     * pretend we have a native Gemini call context.
     */
    if (!geminiToolCallId) {
      geminiModelContent = null;
      geminiToolName = undefined;
    }

    try {
      const rawResult = await runTool(
        normalizedToolCall.tool,
        normalizedToolCall.input
      );

      latestToolResult = sanitizeToolResult(rawResult);
    } catch (error) {
      latestToolResult =
        error instanceof Error
          ? cleanText(
              error.message,
              MAX_TOOL_RESULT_LENGTH
            )
          : "Tool execution failed.";
    }

    /**
     * Continue the loop.
     *
     * Gemini will receive the tool result on the
     * next iteration.
     */
  }

  /**
   * ------------------------------------------------
   * MAX STEPS REACHED
   * ------------------------------------------------
   */
  return {
    reply:
      latestToolResult ||
      "I reached the maximum number of agent steps before completing the request.",
    detectedAction,
    newMemory,
    usedTool,
    tool: lastTool,
    toolResult: latestToolResult ?? null,
    steps,
    toolsUsed,
  };
}
