export type TabType =
  | 'home'
  | 'chat'
  | 'search'
  | 'learn'
  | 'planner'
  | 'profile';

export type UserTier =
  | 'FREE'
  | 'PLUS'
  | 'BUSINESS';

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  preferredLanguage: string;
  country: string;
  tier: UserTier;
  lowDataMode: boolean;
  interests: string[];
  goals: string;
  isGuest: boolean;
}

export interface MemoryItem {
  id: string;
  category:
    | 'preference'
    | 'goal'
    | 'habit'
    | 'fact'
    | 'work';
  content: string;
  createdAt: string;
}

export type PlannerItemType =
  | 'task'
  | 'reminder'
  | 'schedule_block';

export type PriorityType =
  | 'low'
  | 'normal'
  | 'high';

export interface PlannerItem {
  id: string;
  title: string;
  type: PlannerItemType;
  date: string; // YYYY-MM-DD
  time?: string;
  durationMinutes?: number;
  completed: boolean;
  priority: PriorityType;
  category?: string;
  tags?: string[];
}

export interface HabitItem {
  id: string;
  name: string;
  category: string;
  streak: number;
  completedToday: boolean;
  history: string[]; // dates completed
}

export interface SmartAction {
  type:
    | 'TASK'
    | 'REMINDER'
    | 'SCHEDULE'
    | 'BUDGET';
  title: string;
  date?: string;
  time?: string;
  category?: string;
  amount?: number;
  confirmedRequired?: boolean;
}

export interface ChatMessage {
  id: string;
  role:
    | 'user'
    | 'assistant'
    | 'system';
  content: string;
  timestamp: string;
  detectedAction?: SmartAction | null;
  audioAvailable?: boolean;

  /**
   * Optional metadata for richer ChatGPT-style
   * conversation behaviour.
   */
  conversationId?: string;

  /**
   * Indicates whether this message was generated
   * while the AI was using a tool such as search,
   * calculator, planner or another assistant capability.
   */
  toolUsed?: string | null;

  /**
   * Optional source references returned by AI/search.
   */
  sources?: Array<{
    title: string;
    url?: string;
  }>;

  /**
   * Indicates whether the message contains
   * generated or executable code.
   */
  containsCode?: boolean;

  /**
   * Optional model/provider information.
   * Useful for debugging and provider fallback.
   */
  provider?: string;

  model?: string;

  /**
   * Indicates whether this message is still being
   * generated when streaming is enabled.
   */
  isStreaming?: boolean;

  /**
   * Optional error information when a message
   * generation fails.
   */
  error?: string | null;
}

/**
 * A persistent Nodysom AI conversation.
 *
 * Unlike the legacy flat chatHistory array,
 * conversations allow users to maintain multiple
 * independent chats.
 */
export interface Conversation {
  id: string;

  /**
   * User-visible conversation title.
   * Example: "Python Study Plan"
   */
  title: string;

  /**
   * Messages belonging to this conversation.
   */
  messages: ChatMessage[];

  /**
   * Creation timestamp.
   */
  createdAt: string;

  /**
   * Last activity timestamp.
   */
  updatedAt: string;

  /**
   * Optional conversation summary generated by AI.
   */
  summary?: string;

  /**
   * Optional category used for organization.
   */
  category?:
    | 'general'
    | 'study'
    | 'work'
    | 'planning'
    | 'research'
    | 'coding'
    | 'personal'
    | 'other';

  /**
   * Whether this conversation is currently active.
   */
  isActive?: boolean;

  /**
   * Whether the user has archived the conversation.
   */
  isArchived?: boolean;

  /**
   * Whether the conversation is pinned.
   */
  isPinned?: boolean;

  /**
   * Optional custom tags.
   */
  tags?: string[];

  /**
   * Optional AI model/provider used most recently.
   */
  provider?: string;

  model?: string;
}

/**
 * Preferences controlling how Nodysom handles memory.
 */
export interface MemorySettings {
  enabled: boolean;

  /**
   * Automatically allow Nodysom to identify
   * useful long-term preferences/goals.
   */
  autoSave: boolean;

  /**
   * Allow memories to be used when generating
   * personalized responses.
   */
  useInChat: boolean;

  /**
   * Optional timestamp of the last memory cleanup.
   */
  lastReviewedAt?: string;
}

/**
 * A richer representation of a user's AI context.
 *
 * This allows Nodysom to combine profile information,
 * memories, planner information and conversation context.
 */
export interface AIUserContext {
  profile?: UserProfile;

  memories?: MemoryItem[];

  memorySettings?: MemorySettings;

  plannerItems?: PlannerItem[];

  habits?: HabitItem[];

  activeConversationId?: string;

  recentConversations?: Conversation[];

  currentDate?: string;

  currentTime?: string;

  timezone?: string;
}

/**
 * Legacy and current chat storage can coexist.
 *
 * chatHistory is preserved for backward compatibility
 * with the existing application.
 *
 * conversations is the new multi-chat system.
 */
export interface ChatStorage {
  chatHistory: ChatMessage[];

  conversations: Conversation[];

  activeConversationId?: string | null;
}

/**
 * Search result returned by Nodysom's AI search system.
 */
export interface SearchResult {
  query: string;
  summary: string;
  verifiedFacts: string[];
  estimates: string[];
  uncertainties: string[];
  sources: Array<{
    title: string;
    url?: string;
  }>;
  suggestedActions: string[];
}

/**
 * Schedule block used by the planner.
 */
export interface ScheduleBlock {
  time: string;
  title: string;
  category: string;
  durationMinutes?: number;
  notes?: string;
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface Flashcard {
  front: string;
  back: string;
}

export interface LearnModule {
  topic: string;
  difficulty:
    | 'beginner'
    | 'intermediate'
    | 'advanced';
  lessonContent: string;
  keyTakeaways: string[];
  quiz: QuizQuestion[];
  flashcards: Flashcard[];
}
